

INSERT INTO PRODUCT (COD_PRODUCTO,NAME,PRICE,USER_MOD,DATE_MOD) values ('P01','Producto 01',100.00,'USER_TEST',CURRENT_DATE);
INSERT INTO PRODUCT (COD_PRODUCTO,NAME,PRICE,USER_MOD,DATE_MOD) values ('P02','Producto 02',200.00,'USER_TEST',CURRENT_DATE);
INSERT INTO PRODUCT (COD_PRODUCTO,NAME,PRICE,USER_MOD,DATE_MOD) values ('P03','Producto 03',300.00,'USER_TEST',CURRENT_DATE);
INSERT INTO PRODUCT (COD_PRODUCTO,NAME,PRICE,USER_MOD,DATE_MOD) values ('P04','Producto 04',400.00,'USER_TEST',CURRENT_DATE);
