

INSERT INTO PRODUCT (CODE, NAME, DESCRIPTION, PRICE, USER_MOD, DATE_MOD) values ('P01', 'Producto 01', 'Producto 01 description', 100.00, 'USER_LIQ', CURRENT_DATE);
INSERT INTO PRODUCT (CODE, NAME, DESCRIPTION, PRICE, USER_MOD, DATE_MOD) values ('P02', 'Producto 02', 'Producto 02 description', 200.00, 'USER_LIQ', CURRENT_DATE);
INSERT INTO PRODUCT (CODE, NAME, DESCRIPTION, PRICE, USER_MOD, DATE_MOD) values ('P03', 'Producto 03', 'Producto 03 description', 300.00, 'USER_LIQ', CURRENT_DATE);
INSERT INTO PRODUCT (CODE, NAME, DESCRIPTION, PRICE, USER_MOD, DATE_MOD) values ('P04', 'Producto 04', 'Producto 04 description', 400.00, 'USER_LIQ', CURRENT_DATE);
